version: "3.5"
services:
  e_store_mysql:
    image: mysql:5.6
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    container_name: e_store_mysql
    environment:
      - MYSQL_DATABASE=e_store
      - MYSQL_USER=e_store
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    